FROM registry.fedoraproject.org/fedora:38 as unzip

RUN dnf -y install unzip && \
    dnf clean all

# From https://developer.hashicorp.com/nomad/downloads
ARG NAME="nomad"
ARG VERSION="1.6.1"
ARG SHA256="e4c01c51c393b266aee4ff184dd97704ae3d838c233a6189425a9f1c31a55f4f  nomad_1.6.1_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

# From https://github.com/hashicorp/nomad-driver-podman/releases
ARG DRIVER_NAME="nomad-driver-podman"
ARG DRIVER_VERSION="0.5.0"
ARG DRIVER_SHA256="d5fd1a9e6a533c8a78b0f3c4f74f840c039a70a1e23cae216d1329016fd8b91a  nomad-driver-podman_0.5.0_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${DRIVER_NAME}/${DRIVER_VERSION}/${DRIVER_NAME}_${DRIVER_VERSION}_linux_amd64.zip"
RUN echo "${DRIVER_SHA256}" | sha256sum --check
RUN unzip "${DRIVER_NAME}_${DRIVER_VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /nomad .
COPY --from=unzip /nomad-driver-podman .

CMD ["/nomad"]
