FROM registry.fedoraproject.org/fedora:37 as unzip

RUN dnf -y install unzip && \
    dnf clean all

# From https://developer.hashicorp.com/nomad/downloads
ARG NAME="nomad"
ARG VERSION="1.5.2"
ARG SHA256="51d0ecf23f4740d078287eaef2f4da9f3420b087907d33480ef2ec49628d6461  nomad_1.5.2_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

# From https://github.com/hashicorp/nomad-driver-podman/releases
ARG DRIVER_NAME="nomad-driver-podman"
ARG DRIVER_VERSION="0.4.2"
ARG DRIVER_SHA256="bdf7c9f70c79d3d3055e73fdc6212a9bfc221ed824451be2d07b2c62ce4267c4  nomad-driver-podman_0.4.2_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${DRIVER_NAME}/${DRIVER_VERSION}/${DRIVER_NAME}_${DRIVER_VERSION}_linux_amd64.zip"
RUN echo "${DRIVER_SHA256}" | sha256sum --check
RUN unzip "${DRIVER_NAME}_${DRIVER_VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /nomad .
COPY --from=unzip /nomad-driver-podman .

CMD ["/nomad"]
