FROM registry.fedoraproject.org/fedora:38 as unzip

RUN dnf -y install unzip && \
    dnf clean all

# From https://github.com/hashicorp/nomad-driver-podman/releases
ARG DRIVER_NAME="nomad-driver-podman"
ARG DRIVER_VERSION="0.4.2"
ARG DRIVER_SHA256="bdf7c9f70c79d3d3055e73fdc6212a9bfc221ed824451be2d07b2c62ce4267c4  nomad-driver-podman_0.4.2_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${DRIVER_NAME}/${DRIVER_VERSION}/${DRIVER_NAME}_${DRIVER_VERSION}_linux_amd64.zip"
RUN echo "${DRIVER_SHA256}" | sha256sum --check
RUN unzip "${DRIVER_NAME}_${DRIVER_VERSION}_linux_amd64.zip"

FROM registry.fedoraproject.org/fedora:38

# Keep container image for ~2 months
LABEL quay.expires-after=8w

RUN dnf -y update && \
    dnf -y install dnf-plugins-core && \
    dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo && \
    dnf -y install nomad && \
    dnf clean all

RUN mkdir --parents /usr/lib/nomad/plugins
COPY --from=unzip /nomad-driver-podman /usr/lib/nomad/plugins/nomad-driver-podman

CMD ["/usr/bin/nomad"]
