FROM registry.fedoraproject.org/fedora:38 as unzip

# From https://developer.hashicorp.com/consul/downloads
ARG NAME="consul"
ARG VERSION="1.15.3"
ARG SHA256="86c6fe308d2e4eea106d21e20c307726eb87be87eab1f6dfb0d53db81b31d334  consul_1.15.3_linux_amd64.zip"

RUN dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /consul .

CMD ["/consul"]
