FROM registry.fedoraproject.org/fedora:38 as unzip

# From https://developer.hashicorp.com/consul/downloads
ARG NAME="consul"
ARG VERSION="1.16.1"
ARG SHA256="1d48942fa9f1d0df3f56a1622c7a46e9b85924ed9976338912101bb5519aadf1  consul_1.16.1_linux_amd64.zip"

RUN dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /consul .

CMD ["/consul"]
