FROM registry.fedoraproject.org/fedora:38 as unzip

# From https://developer.hashicorp.com/consul/downloads
ARG NAME="consul"
ARG VERSION="1.16.0"
ARG SHA256="c112d1b2ffcfa7d98cde5508bec3bce383ed3650290cc8be3cfe682b79bb13f1  consul_1.16.0_linux_amd64.zip"

RUN dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /consul .

CMD ["/consul"]
