FROM registry.fedoraproject.org/fedora:38 as unzip

# From https://developer.hashicorp.com/vault/downloads
ARG NAME="vault"
ARG VERSION="1.14.0"
ARG SHA256="3d5c27e35d8ed43d861e892fc7d8f888f2fda4319a36f344f8c09603fb184b50  vault_1.14.0_linux_amd64.zip"

RUN dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /vault .

CMD ["/vault"]
