FROM registry.fedoraproject.org/fedora:38 as unzip

# From https://developer.hashicorp.com/vault/downloads
ARG NAME="vault"
ARG VERSION="1.13.3"
ARG SHA256="7ca502f1c50dd043862276705b4ccc1fa45f633345ca7d01fc5b4ba1d820c51e  vault_1.13.3_linux_amd64.zip"

RUN dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /vault .

CMD ["/vault"]
